"use client";
import Link from "next/link";
import { useState } from "react";
import { TxRail } from "@/components/tx-rail";
import { useWallet } from "@/components/wallet-provider";
import { DEMO_LABELS } from "@/lib/demo";
import { DATA_MODE } from "@/lib/genlayer/config";
import { useDatasets } from "@/lib/use-data";
import { useTrackedWrite } from "@/lib/use-tx";

export default function DatasetHome() {
  const datasets = useDatasets(); const wallet = useWallet(); const { tx, run } = useTrackedWrite();
  const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState("Intent Dispute Boundary Set"); const [url, setUrl] = useState(""); const [digest, setDigest] = useState(""); const [schema, setSchema] = useState(JSON.stringify(DEMO_LABELS, null, 2));
  const canWrite = DATA_MODE === "live" && wallet.connected && wallet.correctNetwork; const totalCases = datasets.data.reduce((sum, item) => sum + item.case_count, 0); const resolved = datasets.data.reduce((sum, item) => sum + item.resolved_count, 0); const epochs = datasets.data.reduce((sum, item) => sum + item.epoch_count, 0);
  return <div className="page"><header className="page-header"><div><div className="eyebrow">Authoritative datasets</div><h1>Resolve the labels your annotators disagree on</h1><p>Routine annotation stays local. Ambiguous cases go to GenLayer, where validators apply the rubric and resolved cases become precedent for future disputes.</p></div><button className="quiet-button" onClick={() => setShowCreate(!showCreate)}>+ New Dataset</button></header>
    <div className="summary-stats"><div><b>{datasets.data.length}</b><span>Datasets</span></div><div><b>{totalCases}</b><span>Disputed cases</span></div><div><b>{resolved}</b><span>Resolved</span></div><div><b>{epochs}</b><span>Epochs</span></div></div>
    {datasets.loading && <div className="loading-line" />}{datasets.error && <div className="notice error">{datasets.error}</div>}
    <div className={`work-grid ${showCreate ? "has-create" : ""}`}><section className="main-work"><div className="section-head"><span>Datasets</span><span>Authoritative chain state</span></div><div className="table-scroll"><table className="dataset-table"><thead><tr><th>Dataset</th><th className="numeric">Cases</th><th className="numeric">Resolved</th><th className="numeric">Rubric</th><th /></tr></thead><tbody>{datasets.data.map((dataset) => <tr className="dataset-row" key={dataset.dataset_id}><td><div className="dataset-name">{dataset.name}</div><div className="muted">{JSON.parse(dataset.label_schema_json).length}-label classification</div><div className="mono muted">DS-{String(dataset.dataset_id).padStart(4, "0")}</div></td><td className="numeric">{dataset.case_count}</td><td className="numeric">{dataset.resolved_count}</td><td className="numeric">v{dataset.rubric_version}</td><td><Link className="action-button" href={`/datasets/${dataset.dataset_id}`}>Open Dataset</Link></td></tr>)}</tbody></table></div>{!datasets.loading && datasets.data.length === 0 && <div className="empty-state">No authoritative datasets are readable from the configured source.</div>}</section>
      {showCreate && <aside className="side-work"><div className="section-head"><span>New Dataset</span><button className="plain-button" onClick={() => setShowCreate(false)}>Close</button></div><div className="section-body form-stack"><div className="notice">Publishing creates rubric version 1. Use a public HTTPS rubric and its SHA-256 digest.</div><div className="field"><label>Dataset name</label><input value={name} maxLength={96} onChange={(e) => setName(e.target.value)} /></div><div className="field"><label>Rubric URL</label><input placeholder="https://…" value={url} onChange={(e) => setUrl(e.target.value)} /></div><div className="field"><label>Rubric SHA-256</label><input className="mono" placeholder="64 hex characters" value={digest} onChange={(e) => setDigest(e.target.value)} /></div><details><summary>Label schema</summary><div className="field"><textarea rows={12} value={schema} onChange={(e) => setSchema(e.target.value)} /></div></details><button className="action-button" disabled={!canWrite || !digest} onClick={() => void run("create_dataset", [name, url, digest, schema], datasets.reload)}>Publish Dataset</button>{!wallet.connected && <div className="muted">Connect an injected wallet to enable writes.</div>}{wallet.connected && !wallet.correctNetwork && <div className="danger">StudioNet chain 61999 required.</div>}</div></aside>}
    </div><TxRail state={tx} /></div>;
}
